### ISSUE TITLE
BIOS INT 13h emulation

### ISSUE THREAD

**Issue by ghaerr** [mfld-fr/emu86#18]
Hello @mfld-fr,

Over at ELKS I was reading a discussion where you were helping debug a floppy disk problem several years ago, and you mentioned you were using EMU86 to step through BIOS int 13h (disk I/O service). Did you write int 13h emulation code for EMU86 and/or do you still have it?

I have been thinking of adding BIOS int 13h emulation code to EMU86, that would allow a "standard" ELKS Image file to be mapped into EMU86, booted, and run. The Image file would be passed as an EMU86 parameter and the first block read into memory at 0:7C00. EMU86 could then be used to emulate the PC version of ELKS starting from the boot code!

Is this something you are interested in having added to EMU86?

Thank you!

**Comment by mfld-fr** [comment]
Hello @ghaerr,

Here is the code I used to debug the ELKS early boot in EMU86 : https://github.com/mfld-fr/emu86/commit/23b76652b8a32c063ced1eb34e4c9bbf25707284.

Enjoy !

**Comment by ghaerr** [comment]
Thanks!!
