### ISSUE TITLE
Control-C breaks Linux terminal after exiting

### ISSUE THREAD

**Issue by mfld-fr** [mfld-fr/emu86#31]
Linux terminal is in bad shape after interrupting EMU86 with control-C and then exiting. Used default configuration with mixed debug and console in EMU86 stdio.

**Comment by ghaerr** [comment]
I checked this after sdl branch merge and cannot duplicate, although I will admit that I have seen this infrequently prior. I am guessing that a code path causes an internal EMU86 `exit` call that doesn't call con_term/char_term to reset termios, even though con_term is part of `atexit` chain.

I tried using ">c" (continue) command then ^C, then ">q", but terminal appears normal. Can you get this to duplicate now?

**Comment by mfld-fr** [comment]
Yes, all times with default configuration:
```
mfld@home /mnt/data/home/mfld/advantech/emu86 $ ./elks.sh 
info: load address E0000h
info: load file ../elks-upstream/elks/arch/i86/boot/Image
info: file size=10000h
success: file loaded
info: load address 80000h
info: load file ../elks-upstream/image/romfs.bin
info: file size=2C1A9h
success: file loaded

ELKS Setup Headless console
PC/AT class machine, NEC V20 CPU, 512K base RAM.
ELKS kernel 0.4.0 (31456 text, 0 ftext, 3872 data, 37824 bss, 23840 heap)
Kernel text at e062:0000, data 80:0000, top 8000, 446K free
VFS: Mounted root 0x0600 (romfs filesystem).
No init - running /bin/sh
# pwd
/
# <--- HERE I TYPE ^C
>q
mfld@home /mnt/data/home/mfld/advantech/emu86 $ mfld@home /mnt/data/home/mfld/advantech/emu86 $ mfld@home /mnt/data/home/mfld/advantech/emu86 $  ---> AAARRRGGGHHH !!!
```

**Comment by ghaerr** [comment]
@mfld-fr: thanks, strange. Works on macOS in same scenario.

I will have to setup Linux system to test. Quick code check shows that 'q' typed calls con_term -> char_term -> checks termios.c_oflag (should be non-zero) -> char_normal which resets termios from def_termios.
```
void char_normal ()
    {
    int nonblock = 0;
    fflush(stdout);
    ioctl(0, FIONBIO, &nonblock);
    tcsetattr(0, TCSADRAIN, &def_termios);
    }

int char_init ()
    {
    tcgetattr(0, &def_termios);
    ...
    }


void char_term ()
    {
    if (def_termios.c_oflag) char_normal();
    }
```
Other possibility is `ioctl` isn't working to reset non-blocking mode.

**Comment by mfld-fr** [comment]
It seems that after exiting EMU86, only the 'echo' is missing:
```
mfld@home /mnt/data/home/mfld/advantech/emu86 $ bash: hello : commande introuvable  <--- TYPED 'hello' + CR
mfld@home /mnt/data/home/mfld/advantech/emu86 $ bash: world : commande introuvable  <--- TYPED 'world' + CR
mfld@home /mnt/data/home/mfld/advantech/emu86 $
```
